### ISSUE TITLE
64 Bit compilation breaks because wxSIZE_T_IS_UINT is defined

### ISSUE THREAD

**Issue by Octav14n** [maxmods/wx.mod#1]
wxSIZE_T_IS_UINT is defined while compiling.
On 32 Bit Linux it is needed.
On 64 Bit Linux this breaks compilation.

The effect of its definition is that include/wx/string.h:
```C
#ifndef wxSIZE_T_IS_UINT
    wxUniChar operator[](unsigned int n) const
      { return at(n); }
#endif // size_t != unsigned int
```

isn't compiled. Thus getting really unhelpfull error messages.

**EDIT**: Whops, I mean't to add this here. I wanted to add it to my fork...
Well, Brucey or Derron if you know how to get this fixed so I can fixed or know where this is defined (Ubuntu 14.10 64 Bit) I would be really thankfull.

**Comment by woollybah** [comment]
I haven't got round to building 64-bit yet.
Plan is to (1) sort out remaining issues with the current code and NG, then (2) port to the latest wxWidgets, and then (3) work on 64-bit.

**Comment by Octav14n** [comment]
OK, I've found the error.
32bit Linux has declared wxSIZE_T_IS_UINT explicitly in one of its generated headers.
I'll try to close this issue.
