### ISSUE TITLE
Asserts: Sizer.DoInsert() - ignored alignments

### ISSUE THREAD

**Issue by GWRon** [maxmods/wx.mod#12]
When compiling with current wx.mod I get this on my linux machine:

```
ASSERT INFO:
../src/common/sizer.cpp(2082): assert "!(flags & wxALIGN_CENTRE_VERTICAL)" failed in DoInsert(): Vertical alignment flags are ignored in vertical sizers

BACKTRACE:
[1] zError
[2] __libc_start_main



ASSERT INFO:
../src/common/sizer.cpp(2091): assert "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed in DoInsert(): Horizontal alignment flags are ignored with wxEXPAND

BACKTRACE:
[1] zError
[2] __libc_start_main



ASSERT INFO:
../src/common/sizer.cpp(2100): assert "!(flags & wxALIGN_RIGHT)" failed in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers

BACKTRACE:
[1] zError
[2] __libc_start_main
```

Seems some flags should not be set when a sizer is vertical / horizontal.

**Comment by poregan** [comment]
Wanted to add that I'm seeing the sizer.cpp(2091) assertion on runtime on Windows 8.1 as well.

Using mingw32 & codeblocks' default wx HelloWorld template as a MWE.

**Comment by GWRon** [comment]
Still bugged.

Creating a wxBoxSizer with:
```BlitzMax
Local s:wxBoxSizer = new wxBoxSizer.Create(wxVERTICAL)
```
Leads to 
```
../src/common/sizer.cpp(2082): assert "!(flags & wxALIGN_CENTRE_VERTICAL)" failed in DoInsert(): Vertical alignment flags are ignored in vertical sizers
```

Removing the `wxVERTICAL` then leads to:
```
/BlitzMax/mod/wx.mod/include/wx/sizer.h(951): assert "m_orient == wxHORIZONTAL || m_orient == wxVERTICAL" failed in wxBoxSizer(): invalid value for wxBoxSizer orientation
```

so I assume the sizer.h file is expecting something different to the original library source (common/sizer.cpp). Maybe there are differences between sizer.cpp (in the .a-files) and sizer.h (packaed in wx.mod) ?


Same happens for "wxHORIZONTAL"

**Comment by woollybah** [comment]
Do you have a small, compilable example? :-)

**Comment by woollybah** [comment]
I think the error is concerning whatever it is you are adding inside the wxBoxSizer.
Do you having something with wxALIGN_CENTRE_VERTICAL ?

**Comment by GWRon** [comment]
I am adding elements which are positioned that way

```BlitzMax
Local s:wxBoxSizer = new wxBoxSizer.Create(wxVERTICAL)

local b:wxButton = new wxButton.Create(aPanelOfAWXNotebook, wxID_ANY, 
_("+"))
b.SetMaxSize(30,-1)


s.Add(b, 0, wxALIGN_CENTER_VERTICAL, 5)
```


all of these were generated by wxCodeGen using wxFormBuilder v3.5 (RC1).

**Comment by GWRon** [comment]
I am adding elements which are positioned that way

```BlitzMax
Local s:wxBoxSizer = new wxBoxSizer.Create(wxVERTICAL)

local b:wxButton = new wxButton.Create(aPanelOfAWXNotebook, wxID_ANY, 
_("+"))
b.SetMaxSize(30,-1)

s.Add(b, 0, wxALIGN_CENTER_VERTICAL, 5)
```


all of these were generated by wxCodeGen using wxFormBuilder v3.5 (RC1).

**Comment by woollybah** [comment]
Indeed, and it seems wxWidgets 3.1+ has tightened it's rules on sizers - note Audacity had the same issues which needed fixed.
Better to fix your use of the (now) incorrect alignment ;-)

**Comment by GWRon** [comment]
Thanks.. will have a look at it...  

Thanks #2 for pointing me in the right direction ... I started to narrow it down already (commenting out blocks...and checking the amount of warnings)
