### ISSUE TITLE
wx.mod not compiling

### ISSUE THREAD

**Issue by xlsior75** [maxmods/wx.mod#21]
The latest version of wx.mod is not compiling for me:
gcc 7.1.0, bmk 3.24 mt-win32-x86 / gcc 070100 (cpu x12),bcc[ng] Release Version 0.94, Win10 x64.
Deleted and re-synced all of wx.mod, but error remains:

[ 16%] Processing:common.bmx
[ 16%] Processing:common.bmx
[ 16%] Processing:common.bmx
[Compile Error: Syntax error - expecting identifier.
[c:/code/BlitzmaxNG710/mod/wx.mod/wxcalendarctrl.mod/common.bmx;70;0]
 16%] Processing:common.bmx
[ 16%] Processing:common.bmx
[ 16%]Build Error: failed to compile (-1) c:/code/BlitzmaxNG710/mod/wx.mod/wxcalendarctrl.mod/common.bmx

**Comment by woollybah** [comment]
Oh, sorry, I thought I'd found all the files...

Should be working now.

**Comment by xlsior75** [comment]
OK, that seems to have done it.

As an aside: is there any particular GCC version/distribution that you recommend these days?

**Comment by woollybah** [comment]
The latest wxMax win32 libs have been built with Mingw-w64 7.2.0 rev1, which is also shipped with the latest NG release.

However, I see that 7.3.0 was released recently, so I may migrate to that in the not too distant future.
