### ISSUE TITLE
wxgppanel: DelLayer(layer) not working

### ISSUE THREAD

**Issue by GWRon** [maxmods/wx.mod#26]
When trying to delete a previously added layer, nothing happens.

As the current code contains many stub functions (to remove layers, series, ... aka having more than a "add once and do not alter afterwards" functionality) I tried to circumvent limitations by doing something in the likes of:

```BlitzMax
			If Not graphLayer
				graphLayer = New gpMultiPlotLayer.Create("Layer", "wavelength", "au")
				graphLayer.SetYXFormula("test")
				graphLayer.SetXFormula("nm")
				graphSeries = gpMultiPlotLayer(graphLayer).AddSeriesLayer("test")
				graphPanel.AddLayer(graphLayer)
			Else
				graphPanel.DelAllLayers()
				graphPanel.DelLayer(graphLayer)
				graphPanel.AddLayer(graphLayer)
			EndIf
```
so it (tries to...) removes the multiplotlayer if it was created already. 
But instead of removing, it adds it again, leading to multiple layers being shown.

![double](https://user-images.githubusercontent.com/2625226/43107840-0fa0e472-8edf-11e8-9e76-4b87ce1b63ca.png)

So somehow "deleting layers" does not work yet - albeit it seems to be "wrapped" already.

**Comment by GWRon** [comment]
Here is a complete example with 3 test cases:

- clearing an existing series
- deleting (all) layers
- segfault when deleting an previously added layer

```BlitzMax
SuperStrict

Framework wx.wxApp
Import wx.wxFrame
Import wx.wxgpPanel

New MyApp.run()


Type MyApp Extends wxApp

	Field frame:MyFrame

	Method OnInit:Int()

		frame = MyFrame(New MyFrame.Create(,,"wxWidgets Demo", 50, 50, 850, 640))

		gpTest(frame)
		
		frame.show()
		
		Return True
	
	End Method
	
	Method gpTest(parent:wxWindow)
		
		' A panel is a container for one or more charts
		Local graphPanel:gpPanel = New gpPanel.Create(parent, -1, 240, 336)
		Local multiLayer:gpMultiPlotLayer = New gpMultiPlotLayer.Create("Bar Chart Layer", "sample number", "y")

		' prec datas
		multiLayer.SetType(gpMultiPlotLayer.TYPE_LINE)
		Local sb:gpSeries = multiLayer.AddSeriesLayer("S")
		sb.Invert(False)
		sb.SetPen(wxBLUE_PEN())
		sb.SetBrush(wxBLUE_BRUSH())
		
		sb.DataPush(0, 0)
		sb.DataPush(1, 1)
		sb.DataPush(2, 5)
		sb.DataPush(3, 2)

		graphPanel.AddLayer(multiLayer)
		multiLayer.Refresh()
		multiLayer.RefreshChart()
		graphPanel.Fit(multiLayer)
		
		
Rem
'TEST 1 - not working	
		'now replace the data
		sb.DataClear()
		multiLayer.Refresh()
		multiLayer.RefreshChart()
		graphPanel.Fit(multiLayer)
EndRem		


Rem
'TEST 2 - not working	
		'delete Layers
		graphPanel.DelAllLayers()
		multiLayer.Refresh()
		multiLayer.RefreshChart()
		graphPanel.Fit(multiLayer)
EndRem		


Rem
'TEST 3 - not working	
		'replace Layers
		Local newMultiLayer:gpMultiPlotLayer = New gpMultiPlotLayer.Create("Bar Chart Layer2", "sample number2", "y2")

		newMultiLayer.SetType(gpMultiPlotLayer.TYPE_LINE)
		sb = newMultiLayer.AddSeriesLayer("S2")
		sb.Invert(False)
		sb.SetPen(wxBLUE_PEN())
		sb.SetBrush(wxBLUE_BRUSH())
		
		sb.DataPush(0, 5)
		sb.DataPush(1, 4)
		sb.DataPush(2, 3)
		sb.DataPush(3, 2)

		'DelLayer would cause an EAV ?!
		'graphPanel.DelLayer(multiLayer)
		graphPanel.AddLayer(newMultiLayer)
		multiLayer.Refresh()
		multiLayer.RefreshChart()
		graphPanel.Fit(multiLayer)
EndRem		

	End Method

End Type

Type MyFrame Extends wxFrame

	Method OnInit:Int()
	
		' create a menu bar
	
		Local fileMenu:wxMenu = wxMenu.CreateMenu()
		
		' the "About" item should be in the help menu
		Local helpMenu:wxMenu = wxMenu.CreateMenu()
		
		helpMenu.Append(wxID_ABOUT, "&About...~tF1", "Show about dialog")
		
		fileMenu.Append(wxID_EXIT, "&Quit~tAlt-Q", "Quit this program")
		
		' now append the freshly created menu to the menu bar...
		Local menuBar:wxMenuBar = wxMenuBar.CreateMenuBar()
		menuBar.Append(fileMenu, "&File")
		menuBar.Append(helpMenu, "&Help")

		SetMenuBar(menuBar)
		
		' create a status bar just for fun
		CreateStatusBar()
		SetStatusText("gpPanel sample app")
		
		Connect(wxID_EXIT, wxEVT_COMMAND_MENU_SELECTED, OnQuit)
		Connect(wxID_ABOUT, wxEVT_COMMAND_MENU_SELECTED, OnAbout)
		
	End Method

	Function OnQuit(event:wxEvent)
		' true is to force the frame to close
		wxWindow(event.parent).Close(True)
	End Function
	
	Function OnAbout(event:wxEvent)
		
		wxMessageBox("This is a wxWidgets' gpPanel sample", ..
                 "About gpPanel Sample", ..
                 wxOK | wxICON_INFORMATION, wxWindow(event.parent))
		
	End Function
	
End Type
```

**Comment by GWRon** [comment]
Maybe the whole "Label" thing is not working as expected?

Doing a  `multiLayer.DeleteSeries("S")` leads to an EAV.

Adding a new series after a `multiLayer` got added to a `gpPanel` leads to a non-displayed series. I also tried to call `layer.RefreshChart`, `panel.RealizeLayers()`, `panel.Refresh()` and `panel.RefreshLayer(multiLayer)`... it just does not do what I expect it to do.


As I think the library itself does not have this issue it might be the wrapping (the bmx module) which borks up things somehow. Maybe some API stuff is missing / yet to implement?

**Comment by woollybah** [comment]
From basic inspection, I believe there are issues with the library.
Certainly the "formula"s are not being used in the current codebase. Looking at code from 2016, one could previously set an X formula and have it affect the graph output (eg. scaling). But the current version (that I'm using) just passes through the data to the graph...

I haven't looked at this example in detail yet.

**Comment by GWRon** [comment]
Yes... Formula is misleading as screenshots suggest they were talking about "units" (m, A, V...). And this is what I tried to use it for.
But when setting the "formula" there was no way to remove the "X="-part of the label's "[...]"-section.


If you run the native library example...and append the changes as written above... It should show the same bugged behaviour...



Am 24. Juli 2018 12:39:26 MESZ schrieb Brucey <notifications@github.com>:

**Comment by woollybah** [comment]
I can make 2 delete all layers. However, at that point your ```multiLayer``` will be invalid, so you can't use it after that, and would need to create a new one.

**Comment by GWRon** [comment]
That is odd.. I would assume it just removes a connection instead of trashing a whole object.

Nonetheless I only need a graph panel allowing multiple graphs...and the deletion/replacement of existing ones. So such things/adjustments are okay.

**Comment by woollybah** [comment]
Well, I'd agree, but regardless how I try to disconnect the model from the view, it still seems to want to delete the multiplotlayer when I remove the window from the panel - so presumably there's still something linking them together...

**Comment by GWRon** [comment]
I do not want to demotivate you then... But might wxmathplot be the less bugged graph plotting lib... Regardless of its age?

I mean...if one seriously used the lib such stuff would be obvious. And screenshots//videos suggest that thing are possible...somehow.

**Comment by woollybah** [comment]
I've deprecated wxgppanel. You should probably try wxMathPlot instead.
