### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by xlsior75** [maxmods/wx.mod#28]
compile error with latest bmk/bcc, GCC 7.3.0:

[ 11%] Processing:wxarchive.bmx
[ 11%] Processing:wxarchivefshandler.bmx
[ 11%] Processing:wxclipboard.bmx
[ 11%] Processing:wxfileconfig.bmx
Compile Error: Syntax error - expecting identifier.
[c:/code/BlitzmaxNG730/mod/wx.mod/wxarchive.mod/wxarchive.bmx;129;0]
Build Error: failed to compile (-1) c:/code/BlitzmaxNG730/mod/wx.mod/wxarchive.mod/wxarchive.bmx

**Comment by GWRon** [comment]
The error message is misleading and wrong... It should state that you cannot use a reserved keyword as a variable name.
