### ISSUE TITLE
wxMax2D.mod fails to compile (method definition override differs)

### ISSUE THREAD

**Issue by GWRon** [maxmods/wx.mod#3]
Two lines in wxmax2d.mod/wxmax2d.bmx fail to compile: 

Change line 174:
```BlitzMax
Method AttachGraphics:TMax2DGraphics( widget:Byte Ptr ,flags:Int )
'to
Method AttachGraphics:TMax2DGraphics( widget:Int ,flags:Int )
```

and change line 517:
```BlitzMax
Method AttachGraphics:TwxGraphics( widget:Byte Ptr,flags:Int )
'to
Method AttachGraphics:TwxGraphics( widget:Int,flags:Int )
```

(not creating fork + pull request  because this git repo is just a "mirror" of the google code svn repo)

**Comment by woollybah** [comment]
Okay, I'll need to wrap that in a bmxng clause - widget is really a pointer.

**Comment by woollybah** [comment]
Fixed in SVN.
