### ISSUE TITLE
wx.mod/wxpdfdocument.mod

### ISSUE THREAD

**Issue by xlsior75** [maxmods/wx.mod#33]
MinGW 8,1 latest NG bmk/bcc , wx.mod does not compile, both release and debug:

[ 83%] Compiling:wxtimer.bmx.release.win32.x64.c
[ 83%] Compiling:wxuiactionsimulator.bmx.release.win32.x64.c
[ 83%] Compiling:wxuri.bmx.release.win32.x64.c
[ 83%] Compiling:wxvalidator.bmx.release.win32.x64.c
In file included from c:/code/BlitzmaxNG810/mod/wx.mod/wxpdfdocument.mod/src/pdffontparsertruetype.cpp:44:
c:/code/BlitzmaxNG810/mod/wx.mod/include/wx/msw/private.h: In static member function 'static void* AutoHANDLE<INVALID_VALUE>::InvalidHandle()':
c:/code/BlitzmaxNG810/mod/wx.mod/include/wx/msw/private.h:148:49: error: invalid static_cast from type 'long long unsigned int' to type 'HANDLE' {aka 'void*'}
         return static_cast<HANDLE>(INVALID_VALUE);
                                                 [^ 8
4%] Compiling:common.bmx.release.win32.x64.c
[ 84%] Compiling:common.bmx.release.win32.x64.c
[ 84%] Compiling:common.bmx.release.win32.x64.c
[ 84%] Compiling:common.bmx.release.win32.x64.c
[ 84%] Compiling:common.bmx.release.win32.x64.c
[ 84%] Compiling:common.bmx.release.win32.x64.c
[ 84%] Compiling:common.bmx.release.win32.x64.c
[ 84%] Compiling:common.bmx.release.win32.x64.c
[ 84%] Compiling:common.bmx.release.win32.x64.c
[ 84%] Compiling:common.bmx.release.win32.x64.c
Build Error: failed to compile (1) c:/code/BlitzmaxNG810/mod/wx.mod/wxpdfdocument.mod/src/pdffontparsertruetype.cpp

**Comment by xlsior75** [comment]
I saw you did an update to this module a few weeks ago, but still seeing a similar errors on compilation

**Comment by xlsior75** [comment]
Any idea?

**Comment by woollybah** [comment]
It's seems to be a bug with wxWidgets itself. I'm working on a new release.

**Comment by woollybah** [comment]
Should be working now. Apologies.
