### ISSUE TITLE
after building any of the included wx samples on windows

### ISSUE THREAD

**Issue by braxtonrivers** [maxmods/wx.mod#36]
The following exception is thrown

Mismatch between the program and library build versions detected.
The Library used 3.1.1 (wchar_t, compiler with C++ ABI 1011, wx containers, compatible with 3.0),
and your program used 3.1.1 (wchar_t, compiler with C++ ABI 1012, wx containers, compatible with 3.0).

When using the latest wx version freshly checked out on windows, also wxpdfdocument.mod has to be removed in order to build wx as this module produces the following message

In file included from D:/BlitzMax/mod/wx.mod/wxpdfdocument.mod/wxpdfdoc/src/pdffontparsertruetype.cpp:40:
D:/BlitzMax/mod/wx.mod/include/wx/msw/private.h: In static member function 'static void* AutoHANDLE<INVALID_VALUE>::InvalidHandle()':
D:/BlitzMax/mod/wx.mod/include/wx/msw/private.h:148:49: error: invalid static_cast from type 'long long unsigned int' to type 'HANDLE' {aka 'void*'}
         return static_cast<HANDLE>(INVALID_VALUE);
                                                 ^
Build Error: failed to compile (1) D:/BlitzMax/mod/wx.mod/wxpdfdocument.mod/wxpdfdoc/src/pdffontparsertruetype.cpp

**Comment by GWRon** [comment]
On linux I had to recompile the wx-libraries, maybe this is needed for you too? Somewhere Brucey stored the configuration he used when generating the DLL-files. Use it to compile wxwidgets on your own and replace the wxmax'wxwidget-files with the generated files.

Or wait for Brucey and spare time to generate the files (takes a bit :-))

**Comment by braxtonrivers** [comment]
Thankyou I will try to compile wxwidgets on windows and see how that goes.

**Comment by woollybah** [comment]
Apologies. The latest win32 wx.mod has now been compiled with gcc 8.1.0 (which matches the current release of NG)
