### ISSUE TITLE
Missing "-std=gnu++11" in all wx.mod-modules

### ISSUE THREAD

**Issue by GWRon** [maxmods/wx.mod#4]
Modules need `ModuleInfo "CC_OPTS: -std=gnu++11"` when compiling for `?win32`.

As the project here is a replicate of the google code svn I am mailing a patch file to Brucey.

**Comment by Octav14n** [comment]
for Linux they need that info too. I don't know if your line works but:
``` 
ModuleInfo "CC_OPTS: -std=c++11"
```
Worked for me on Ubuntu 14.10.

I just added this line to each "common.bmx" to compile this module.

**Comment by GWRon** [comment]
Tedious job :smile: 

I compiled it here on Linux Mint 17 64Bit without that line - but `gcc -v` is saying I am still on 4.8.2.

So I think Brucey might end up adding it to "all" targets ... @woollybah - feel free to ignore my .patch file.

**Comment by woollybah** [comment]
But what happens if you are using a library that hasn't been built with c++11/gnu++11 ? The library itself was not - as it was built with 4.8.x. Presumably it would require to be built with the same settings?
I'll have a look at upgrading to the latest TDM and see how things go on Win32.
So 4.9.x+ requires the flag on all versions, potentially...

**Comment by GWRon** [comment]
I do not know what happens if you import another 3rd party module....

Regarding wx alone: couldn't there be a single file having these flags and all the other linker options all of the modules share? Would save the need to adjust 220 files...

Another option..but only for NG is the introduction of dynamic conditionals... `?mingw49`... so things could be done differently depending on the used environment.

Am 22. Februar 2015 00:05:05 MEZ, schrieb Brucey <notifications@github.com>:

**Comment by woollybah** [comment]
I haven't used this setting on any builds for the latest code - even on Windows.
It may have been [a bug in wxwidgets](http://wxwidgets.blogspot.com/2015/06/build-fixes-for-different-gcc.html) ?
Or not.. I haven't personally had this issue yet, so I dunno.

**Comment by woollybah** [comment]
The latest wxMax should be clean-building across platforms.
