### ISSUE TITLE
howto: SetIcon("bmk added .rc icon" or incbin)

### ISSUE THREAD

**Issue by GWRon** [maxmods/wx.mod#40]
Question: how to set the icon of a frame to the one set as app icon ("ICON" in the rc file) by bmk?

If that isn't as easy... How to set the icon to an incbinned icon?
Code seems to support "::" but I then get an error that "isOk()" fails.

**Comment by woollybah** [comment]
I'm going to make a change to the way we are currently storing the icon in the resource. It's currently stored as 101, but that's difficult to use from a higher level. So I'm going to set it to "APP_ICON" instead.
Once that's done, wxIcon will need a new constructor to take a resource name, which you will be able to pass in the text "APP_ICON" and then you will have a handle on the icon for setting on your frame.

**Comment by woollybah** [comment]
That seems to work :-)
```
...
frame.SetIcon(wxIcon.CreateFromResource("APP_ICON"))
...
```

**Comment by woollybah** [comment]
You'll need the latest bmk (`make.bmk`), brl.mod and wxMax to try it out.

**Comment by GWRon** [comment]
Will do that later.

Do not close the issue afterwards... Incbin support is still open.

**Comment by woollybah** [comment]
Example :
```blitzmax
SuperStrict

Framework wx.wxApp
Import wx.wxFrame
Import brl.ramstream

Incbin "icon_test2.ico"

Type MyApp Extends wxApp

	Field frame:wxFrame

	Method OnInit:Int()
		wxInitAllImageHandlers()
		
		frame = wxFrame.CreateFrame(,,"Hello World", 100, 100)
		frame.SetIcon(wxIcon.CreateFromFile("incbin::icon_test2.ico", wxBITMAP_TYPE_ICO))
		frame.show()
	
		Return True
	
	End Method

End Type

New MyApp.run()
```
Important things... `brl.ramstream` and initialising image handlers.

**Comment by GWRon** [comment]
Ahhh i tried exactly that...but without ramstream ... Explains why it wasn't working.
